cvs add -m 'Merge Bogart into Head'  model/assignment/DefaultAssignmentEdit.php
cvs add -m 'Merge Bogart into Head'  model/assignment/DefaultAssignmentView.php
cvs add -m 'Merge Bogart into Head'  model/assignment/GwpsAssignmentEdit.php
cvs add -m 'Merge Bogart into Head'  model/assignment/GwpsAssignmentView.php
cvs add -m 'Merge Bogart into Head'  view/component/assignHistoryView.tpl
cvs add -m 'Merge Bogart into Head'  view/component/e2eAssignButtonTab.tpl
cvs add -m 'Merge Bogart into Head'  view/component/workFlowForEditing.tpl
cvs add -m 'Merge Bogart into Head'  view/config/text.conf
cvs add -m 'Merge Bogart into Head'  view/layout/frame.tpl
cvs add -m 'Merge Bogart into Head'  view/layout/head.tpl
cvs add -m 'Merge Bogart into Head'  view/layout/leftnav.tpl
cvs add -m 'Merge Bogart into Head'  view/layout/popup.tpl
cvs add -m 'Merge Bogart into Head'  view/layout/rightcol.tpl
cvs add -m 'Merge Bogart into Head'  view/page/asig/alltaskclientview.tpl
cvs add -m 'Merge Bogart into Head'  view/page/asig/alltaskheadview.tpl
cvs add -m 'Merge Bogart into Head'  view/page/asig/alltaskotherview.tpl
cvs add -m 'Merge Bogart into Head'  view/page/asig/alltaskwplpmview.tpl
cvs add -m 'Merge Bogart into Head'  view/page/asig/closeorcanceldropdown.tpl
cvs add -m 'Merge Bogart into Head'  view/page/asig/grouptaskclientview.tpl
cvs add -m 'Merge Bogart into Head'  view/page/asig/grouptaskotherview.tpl
cvs add -m 'Merge Bogart into Head'  view/page/asig/grouptaskwplpmview.tpl
cvs add -m 'Merge Bogart into Head'  view/page/asig/mytasksforclientview.tpl
cvs add -m 'Merge Bogart into Head'  view/page/asig/mytasksforwplorpmview.tpl
cvs add -m 'Merge Bogart into Head'  view/page/asig/mytasksview.tpl
cvs add -m 'Merge Bogart into Head'  view/page/asig/mytasksviewforpublisher.tpl
cvs add -m 'Merge Bogart into Head'  view/page/asig/projectheadview.tpl
cvs add -m 'Merge Bogart into Head'  view/page/asig/taskfilterview.tpl
cvs add -m 'Merge Bogart into Head'  view/page/asig/teamheadview.tpl
cvs add -m 'Merge Bogart into Head'  view/page/asig/taskdetail/assignment_end.tpl
cvs add -m 'Merge Bogart into Head'  view/page/asig/taskdetail/assignment_start.tpl
cvs add -m 'Merge Bogart into Head'  view/page/asig/taskdetail/default_searchoptim_edit.tpl
cvs add -m 'Merge Bogart into Head'  view/page/asig/taskdetail/default_searchoptim_view.tpl
cvs add -m 'Merge Bogart into Head'  view/page/asig/taskdetail/default_taskdata_edit.tpl
cvs add -m 'Merge Bogart into Head'  view/page/asig/taskdetail/default_taskdata_view.tpl
cvs add -m 'Merge Bogart into Head'  view/page/asig/taskdetail/default_taskdetail_edit.tpl
cvs add -m 'Merge Bogart into Head'  view/page/asig/taskdetail/default_taskdetail_view.tpl
cvs add -m 'Merge Bogart into Head'  view/page/asig/taskdetail/default_workflowdetail_edit.tpl
cvs add -m 'Merge Bogart into Head'  view/page/asig/taskdetail/default_workflowdetail_view.tpl
cvs add -m 'Merge Bogart into Head'  view/page/asig/taskdetail/gwps_searchoptim_edit.tpl
cvs add -m 'Merge Bogart into Head'  view/page/asig/taskdetail/gwps_searchoptim_view.tpl
cvs add -m 'Merge Bogart into Head'  view/page/asig/taskdetail/gwps_taskdata_edit.tpl
cvs add -m 'Merge Bogart into Head'  view/page/asig/taskdetail/gwps_taskdata_view.tpl
cvs add -m 'Merge Bogart into Head'  view/page/asig/taskdetail/gwps_workflowdetail_edit.tpl
cvs add -m 'Merge Bogart into Head'  view/page/asig/taskdetail/gwps_workflowdetail_view.tpl
cvs add -m 'Merge Bogart into Head'  view/page/asig/taskdetail/workflowtableview.tpl
cvs add -m 'Merge Bogart into Head'  view/page/asig/taskdetail/jss/common_assignment.js
cvs add -m 'Merge Bogart into Head'  view/page/asig/taskdetail/jss/default_assignment_edit.js
cvs add -m 'Merge Bogart into Head'  view/page/asig/taskdetail/jss/default_assignment_view.js
cvs add -m 'Merge Bogart into Head'  view/page/asig/taskdetail/jss/gwps_assignment_edit.js
cvs add -m 'Merge Bogart into Head'  view/page/asig/taskdetail/jss/gwps_assignment_view.js
cvs add -m 'Merge Bogart into Head'  view/page/proj/basicTaskTable.html
cvs add -m 'Merge Bogart into Head'  view/page/proj/basicTaskTableForPublisher.html
cvs add -m 'Merge Bogart into Head'  view/page/proj/basicTaskTableForPublisherTab.html
cvs add -m 'Merge Bogart into Head'  view/page/proj/basicTaskTableTab.html
cvs add -m 'Merge Bogart into Head'  view/page/proj/projectMainPage.html
cvs add -m 'Merge Bogart into Head'  view/page/proj/projectMainPageTab.html
cvs add -m 'Merge Bogart into Head'  view/page/proj/taskTableForClient.html
cvs add -m 'Merge Bogart into Head'  view/page/proj/taskTableForClientTab.html
cvs add -m 'Merge Bogart into Head'  view/page/queue/nonwdlview.tpl
cvs add -m 'Merge Bogart into Head'  view/page/queue/nonwdlviewforpmorpublish.tpl
cvs add -m 'Merge Bogart into Head'  view/page/queue/wdlview.tpl
cvs add -m 'Merge Bogart into Head'  view/page/sod/add.tpl
cvs add -m 'Merge Bogart into Head'  view/page/sod/approve.tpl
cvs add -m 'Merge Bogart into Head'  view/page/sod/edit.tpl
cvs add -m 'Merge Bogart into Head'  view/page/sod/exception.tpl
cvs add -m 'Merge Bogart into Head'  view/page/sod/notify.tpl
cvs add -m 'Merge Bogart into Head'  view/page/sod/reason.tpl
cvs add -m 'Merge Bogart into Head'  view/page/sod/renew.tpl
cvs add -m 'Merge Bogart into Head'  view/page/sod/sod.tpl
cvs add -m 'Merge Bogart into Head'  view/page/sod/sod_exception_rule.tpl
cvs add -m 'Merge Bogart into Head'  view/page/sod/view.tpl
cvs add -m 'Merge Bogart into Head'  view/page/tool/timeestimator/TimeEstimator_view.tpl
cvs add -m 'Merge Bogart into Head'  view/page/tool/timeestimator/timeestimator_admin_list.tpl
cvs add -m 'Merge Bogart into Head'  view/page/tool/timeestimator/timeestimator_edit_et.tpl
cvs add -m 'Merge Bogart into Head'  view/page/tool/timeestimator/timeestimator_edit_section.tpl
cvs add -m 'Merge Bogart into Head'  view/page/tool/timeestimator/timeestimator_fix_v17.css
cvs add -m 'Merge Bogart into Head'  view/page/tool/timeestimator/timeestimator_view_et.tpl
cvs add -m 'Merge Bogart into Head'  view/page/wse/wsetaskadd.tpl
cvs add -m 'Merge Bogart into Head'  view/page/wse/wsetaskcomments.tpl
cvs add -m 'Merge Bogart into Head'  view/page/wse/wsetaskview.tpl
cvs add -m 'Merge Bogart into Head'  view/page/wse/wseworkflowview.tpl
